
import { SheetRunningOrder } from '../RunningOrder'

import * as cellData from './cellValues.json'

describe('RunningOrders', () => {

	it('should exist', () => {
		let a = new SheetRunningOrder('test', 'some name', new Date(1), new Date(2))
		expect(a).toBeTruthy()
	})
	it('should correctly parse 2d cell array', () => {
		let a = SheetRunningOrder.fromSheetCells('sheetId123', 'name', (cellData as any).values)
		expect(a).toBeTruthy()

		expect(a.id).toEqual('sheetId123')
		expect(a.name).toEqual('name')
		expect(a.expectedStart).toEqual(new Date(1577685600000))
		expect(a.expectedEnd).toEqual(new Date(1577685600000 + 30 * 60 * 1000))
		expect(a.sections.length).toBe(10)
	})
	it('Diff undefined should return "Deleted" change', () => {
		let a = SheetRunningOrder.fromSheetCells('sheetId123', 'name', (cellData as any).values)
		let diff = a.diff(undefined)
		expect(diff.changeType).toEqual('Deleted')
	})
	it('Diff itself should return "Unchanged" change', () => {
		let a = SheetRunningOrder.fromSheetCells('sheetId123', 'name', (cellData as any).values)
		let diff = a.diff(a)
		expect(diff.changeType).toEqual('Unchanged')
		expect(diff.sections.length).toEqual(0)
	})
	it('Diff identical should return "Unchanged" change', () => {
		let a = SheetRunningOrder.fromSheetCells('sheetId123', 'name', (cellData as any).values)
		let b = SheetRunningOrder.fromSheetCells('sheetId123', 'name', (cellData as any).values)
		let diff = a.diff(b)
		expect(diff.changeType).toEqual('Unchanged')
		expect(diff.sections.length).toEqual(0) // Will not work right now as the id's are not set
	})
	describe('#columnToLetter', () => {
		it('returns correct values', () => {
			expect(SheetRunningOrder.columnToLetter(0)).toEqual('')
			expect(SheetRunningOrder.columnToLetter(1)).toEqual('A')
			expect(SheetRunningOrder.columnToLetter(2)).toEqual('B')
			expect(SheetRunningOrder.columnToLetter(3)).toEqual('C')
			expect(SheetRunningOrder.columnToLetter(4)).toEqual('D')
			expect(SheetRunningOrder.columnToLetter(5)).toEqual('E')
			expect(SheetRunningOrder.columnToLetter(6)).toEqual('F')
			expect(SheetRunningOrder.columnToLetter(7)).toEqual('G')
			expect(SheetRunningOrder.columnToLetter(8)).toEqual('H')
			expect(SheetRunningOrder.columnToLetter(9)).toEqual('I')
			expect(SheetRunningOrder.columnToLetter(10)).toEqual('J')
			expect(SheetRunningOrder.columnToLetter(11)).toEqual('K')
			expect(SheetRunningOrder.columnToLetter(12)).toEqual('L')
			expect(SheetRunningOrder.columnToLetter(13)).toEqual('M')
			expect(SheetRunningOrder.columnToLetter(14)).toEqual('N')
			expect(SheetRunningOrder.columnToLetter(15)).toEqual('O')
			expect(SheetRunningOrder.columnToLetter(16)).toEqual('P')
			expect(SheetRunningOrder.columnToLetter(17)).toEqual('Q')
			expect(SheetRunningOrder.columnToLetter(18)).toEqual('R')
			expect(SheetRunningOrder.columnToLetter(19)).toEqual('S')
			expect(SheetRunningOrder.columnToLetter(20)).toEqual('T')
			expect(SheetRunningOrder.columnToLetter(21)).toEqual('U')
			expect(SheetRunningOrder.columnToLetter(22)).toEqual('V')
			expect(SheetRunningOrder.columnToLetter(23)).toEqual('W')
			expect(SheetRunningOrder.columnToLetter(24)).toEqual('X')
			expect(SheetRunningOrder.columnToLetter(25)).toEqual('Y')
			expect(SheetRunningOrder.columnToLetter(26)).toEqual('Z')
			expect(SheetRunningOrder.columnToLetter(27)).toEqual('AA')
			expect(SheetRunningOrder.columnToLetter(28)).toEqual('AB')
			expect(SheetRunningOrder.columnToLetter(29)).toEqual('AC')
			expect(SheetRunningOrder.columnToLetter(30)).toEqual('AD')
			expect(SheetRunningOrder.columnToLetter(31)).toEqual('AE')
			expect(SheetRunningOrder.columnToLetter(32)).toEqual('AF')
			expect(SheetRunningOrder.columnToLetter(33)).toEqual('AG')
			expect(SheetRunningOrder.columnToLetter(34)).toEqual('AH')
			expect(SheetRunningOrder.columnToLetter(35)).toEqual('AI')
			expect(SheetRunningOrder.columnToLetter(36)).toEqual('AJ')
			expect(SheetRunningOrder.columnToLetter(37)).toEqual('AK')
			expect(SheetRunningOrder.columnToLetter(38)).toEqual('AL')
			expect(SheetRunningOrder.columnToLetter(39)).toEqual('AM')
			expect(SheetRunningOrder.columnToLetter(40)).toEqual('AN')
			expect(SheetRunningOrder.columnToLetter(41)).toEqual('AO')
			expect(SheetRunningOrder.columnToLetter(42)).toEqual('AP')
			expect(SheetRunningOrder.columnToLetter(43)).toEqual('AQ')
			expect(SheetRunningOrder.columnToLetter(44)).toEqual('AR')
			expect(SheetRunningOrder.columnToLetter(45)).toEqual('AS')
			expect(SheetRunningOrder.columnToLetter(46)).toEqual('AT')
			expect(SheetRunningOrder.columnToLetter(47)).toEqual('AU')
			expect(SheetRunningOrder.columnToLetter(48)).toEqual('AV')
			expect(SheetRunningOrder.columnToLetter(49)).toEqual('AW')
			expect(SheetRunningOrder.columnToLetter(50)).toEqual('AX')
			expect(SheetRunningOrder.columnToLetter(51)).toEqual('AY')
			expect(SheetRunningOrder.columnToLetter(52)).toEqual('AZ')
			expect(SheetRunningOrder.columnToLetter(53)).toEqual('BA')
			expect(SheetRunningOrder.columnToLetter(54)).toEqual('BB')
			expect(SheetRunningOrder.columnToLetter(55)).toEqual('BC')
			expect(SheetRunningOrder.columnToLetter(56)).toEqual('BD')
			expect(SheetRunningOrder.columnToLetter(57)).toEqual('BE')
			expect(SheetRunningOrder.columnToLetter(26 * 26 + 27)).toEqual('AAA')
			expect(SheetRunningOrder.columnToLetter(26 * 26 * 27 + 27)).toEqual('AAAA')
		})
	})
})
